inaka/worker_pool

- rebar.config
[This guideline](https://github.com/inaka/erlang_guidelines#prefer-the-git-protocol-over-others-when-specifying-dependency-urls)
> Respect the git://… guideline

- src/wpool_sup.erl
If the wpool_pool supervisor exits because it hits the worker restart intensity limit, wpool_sup does not restart the pool.
wpool_sup is the parent supervisor to wpool_pool supervisors.  wpool_pool supervises the workers in a worker pool. wpool_sup uses the 'transient' restart strategy. The 'transient' restart strategy restarts the child if the child exit reason is not 'normal', 'shutdown', or {'shutdown', Term}. If a supervisor terminates because it hits the restart intensity limit, the exit reason is 'shutdown'. Should this occur, wpool_sup will not restart the failed supervisor.
> worker pools do not restart after hitting the restart intensity limit

- src/wpool.erl
- src/wpool_pool.erl
- src/wpool_process_sup.erl
- test/echo_server.erl
- test/wpool_pool_SUITE.erl
wpool_pool supervises the wpool_queue_manager and workers. It is a one_for_one supervisor.
When a worker (wpool_process) starts, it registers itself as available with wpool_queue_manager. wpool_queue_manager uses the loop State variable to keep track of available workers. If wpool_queue_manager crashes, it loses this state information. Because the wpool_pool supervisor is one_for_one, wpool_queue_manger restarts after a crash, but the workers continue running and do not know to reregister. Hence, after a wpool_queue_manager crash, work is never assigned because the wpool_queue_manager does not appear to have any available workers.
Suggestion - rearrange the supervision tree so that there is a one_to_one wpool_process_sup that manages the workers. Make this a child to the wpool_pool …
> wpool_queue_manager crash cripples worker pool

- src/wpool_process.erl
- test/wpool_process_SUITE.erl
It is common when initializing a gen_server to avoid potentially slow
setup in the init function itself and to use a short timeout to to
additional setup such as connecting to a server.
This patch makes wpool_process handle the case when gen_server:init
returns a tuple with a timeout.
> Handle gen_server:init return with timeout

- README.md
- elvis.config
- src/wpool.erl
- src/wpool_pool.erl
- test/wpool_fsm_pool_SUITE.erl
- test/wpool_pool_SUITE.erl
In the `available_worker` strategy the timeout for getting the worker is added to the timeout for the job's execution. This prevents a fail fast approach where an error regarding no available workers could be reported almost immediately.
What I like is a fail fast approach, when you can reply with an error within 0.1s or so if there is no spare worker.
> Fail fast if there is no spare workers in the pool

- rebar.config
While you are using erlang.mk, maybe we should add `rebar.config` as an app dependency:
```
app:: rebar.config
```
http://erlang.mk/guide/compat.html
It promises to generate correct `rebar.config` file.
With the current one (https://github.com/inaka/worker_pool/blob/bfef604428927354bbe5586d547a8e30b49e5650/rebar.config), I am getting: "can't find include lib "mixer/include/mixer.hrl"" error during `rebar3 compile`.
master: https://github.com/inaka/worker_pool/commit/df42128ed73a7d085f6068be5b4bcdfc9013a33d
> master is not working with rebar3 projects

- Makefile
- rebar.config
- src/wpool_pool.erl
Once everybody fully migrated to R18, drop the change from #26 and just replace the `random` module by the new `rand`
> Properly change the random implementation for R18

- src/wpool.erl
The function is not really doing anything that `wpool:call/4` is not doing.
Even when it would break backwards compatibility, for the sake of simplicity I would remove it.
> Remove wpool:call/5

- src/wpool.erl
- src/wpool_fsm_process.erl
- src/wpool_fsm_worker.erl
- src/wpool_pool.erl
- src/wpool_process.erl
- src/wpool_queue_manager.erl
- src/wpool_sup.erl
- src/wpool_worker.erl
- test/echo_server.erl
- test/wpool_SUITE.erl
- test/wpool_fsm_pool_SUITE.erl
- test/wpool_fsm_process_SUITE.erl
- test/wpool_fsm_worker_SUITE.erl
- test/wpool_meta_SUITE.erl
- test/wpool_pool_SUITE.erl
- test/wpool_process_SUITE.erl
- test/wpool_worker_SUITE.erl
Many functions, like ``wpool_queue_manager:proc_info`` are not tested at all.
> Complete Test Coverage

- src/wpool_pool.erl
- test/wpool_process_SUITE.erl
Also got rid of the microoptimization around zero-length queue, it only serves to make code more confusing, as lists:min would select that zero anyway. As the code there got even more confusing, I chose to get rid of it.
Closes #94.
> Prevent wpool_pool from crashing on dead workers with best_worker strategy.

- src/wpool_fsm_process.erl
- src/wpool_queue_manager.erl
- test/wpool_SUITE.erl
Now it follows the "cast a call" paradigm for all types of all calls,
and all_state_events are now queued correctly, too.
Fixes #93.
> Added monitoring to sync calls & made all sync calls the same scheme.

- src/wpool_process.erl
- test/wpool_process_SUITE.erl
Perhaps it had historical significance, but as of right now,
wpool_process uses ordinary gen_server reply facilities, and we can
safely pass on noreply results.
If a worker chose to handle a message later, then it is its own
responsibility, honestly.
Closes #78.
> Got rid of can_not_hold_a_reply error.

- src/wpool_fsm_worker.erl
- src/wpool_pool.erl
- src/wpool_worker.erl
- test/wpool_fsm_worker_SUITE.erl
- test/wpool_worker_SUITE.erl
The general convention of Erlang is such that "throws" are nonlocal returns (untouched by catch(), but mangled upon process exit), errors are runtime errors (where things are not where they're supposed to be, like badarg, badkey or whatever), and exits are the "missing part of the system" exception (if you don't handle it, you should be restarted). This is why no function in standard library, and many community libraries too, returns by throw: it's intended for internal use (also it messed up OTP code).
In worker_pool in particular, what is logically a "resource unavailable" error (e.g. timeout or straight up missing pool) and would be an exit in OTP is instead signalled by throw. This breaks the convention and requires thus special handling in places that could've just been "on exit, …
> Misuse of throw() in the interface code

- rebar.config
New Erlang releases can introduce new warnings and deprecations, and since we don't always control end user's environment, this option can cause problems for downstream.
Example of downstream problems: https://github.com/esl/MongooseIM/issues/1340 (Erlang 20 added a warning for `export_all` as well as deprecated `gen_fsm`).
> Remove warnings_as_errors compile opt.

- elvis.config
- rebar.config
- src/wpool_pool.erl
- test/wpool_meta_SUITE.erl
```erlang
1> wpool:stats(harry).
[{pool,harry},
{supervisor,<0.350.0>},
{options,[{workers,11},
{overrun_warning,infinity},
{overrun_handler,{error_logger,warning_report}},
{workers,100},
{worker_opt,[]}]},
{size,11},
{next_worker,1},
{total_message_queue_len,0},
{workers,[{11,[{message_queue_len,0},{memory,1712}]},
{10,[{message_queue_len,0},{memory,1712}]},
{9,[{message_queue_len,0},{memory,1712}]},
{8,[{message_queue_len,0},{memory,1712}]},
{7,[{message_queue_len,0},{memory,1712}]},
{6,[{message_queue_len,0},{memory,1712}]},
{5,[{message_queue_len,0},{memory,1712}]},
{4,[{message_queue_len,0},{memory,1712}]},
{3,[{message_queue_len,0},{memory,1712}]},
{2,[{message_queue_len,0},{memory,1712}]},
{1,[{message_queue_len,0},{memory,1712}]}]}]
```
As you can see under the `options` key, the …
> Remove repeated "worker" option from wpool:stats/1 output

- src/wpool_queue_manager.erl
When a worker is killed by some reason (as when then maximum heap size
is reached), the client is not receiving any information about it but a
timeout. With this patch it will receive exit(killed, {gen_server, call,
[Worker, Call, Timeout]}) as with other exit reasons.
Closes inaka/worker_pool#141
> Propagate `killed` reason to clients

- src/wpool_sup.erl
This PR is to branch `rel-3.1` as we need this change in [esl/MongooseIM](https://github.com/esl/MongooseIM) but are not able to use current master branch of `worker_pool` since we still want to support Erlang/OTP 19 and 20 in MongooseIM.
> Improve function spec in wpool_sup

- README.md
- src/wpool.erl
- src/wpool_process.erl
- src/wpool_time_checker.erl
- src/wpool_utils.erl
- test/wpool_SUITE.erl
This feature allows to kill an overran task after N overrun
warning messages. The worker will be killed forcing the tasks
to be finished.
The original use case is to cancel a task after it had reached its
configured time out, avoiding the server to be loaded with tasks
which results will not be used by any client.
> Kill a overran worker

- include/wpool.hrl
- src/wpool_pool.erl
- src/wpool_queue_manager.erl
- test/wpool_SUITE.erl
Move `wpool` record into `wpool_pool` with its own opaque type and use that instead of sharing `wpool.h` everywhere.
> Turn #wpool into an ODS

- README.md
- src/wpool.erl
- src/wpool_process.erl
- src/wpool_time_checker.erl
- src/wpool_utils.erl
- test/wpool_SUITE.erl
This feature allows to kill an overran task. As a proof of concept
the check condition on this commit is a maximum number of overrun
warning messages. The worker will be killed forcing the tasks
to be finished.
The original use case is to cancel a task after it had reached its
configured time out, avoiding the server to be loaded with tasks
which results will not be used by any client.
[Fixes #150]
> Kill an overran worker

- rebar.config
- test/echo_server.erl
- test/wpool_SUITE.erl
- test/wpool_meta_SUITE.erl
- test/wpool_pool_SUITE.erl
- test/wpool_process_SUITE.erl
- test/wpool_worker_SUITE.erl
As @michalwski correctly points out in #137 comments, `timer:sleep` is not a good thing to use, specially not in CI tests, that's why CT provides `ct:sleep` as a replacement. But we know better, we have `ktn_task:wait_for` so that's the one we should use.
> Move from timer:sleep to ktn_task:wait_for in tests

- .travis.yml
- README.md
- rebar.config
> [#154] adding integration with Travis+Codecov

- elvis.config
- rebar.config
- src/wpool_pool.erl
- test/sleepy_server.erl
- test/wpool_SUITE.erl
A minimal test that can be run on the shell:
```erlang
wpool:start().
wpool:start_pool(test, [{workers, 3}]). 
exit(whereis('wpool_pool-test-1'), kill), wpool:stats().
```
Sometimes, this produces the following error:
```erlang
22> wpool:stats().
[[{pool,test},
{supervisor,<0.6846.0>},
{options,[{max_overrun_warnings,infinity},
{overrun_handler,{error_logger,warning_report}},
{overrun_warning,infinity},
{queue_type,fifo},
{worker_opt,[]},
{workers,3}]},
{size,3},
{next_worker,1},
{total_message_queue_len,0},
{workers,[{3,[{message_queue_len,0},{memory,2832}]},
{2,[{message_queue_len,0},{memory,2832}]},
{1,[{message_queue_len,0},{memory,2832}]}]}]]
23> exit(whereis('wpool_pool-test-1'), kill), wpool:stats().
** exception error: no match of right hand side value undefined
in function …
```
> wpool:stats() might crash after a worker is killed

- README.md
- src/wpool_process_sup.erl
- test/wpool_SUITE.erl
The  `shutdown` option in the child specs for each worker is hardcoded to 5000 ms. If something is slow during shutdown, this may add up to quite a lot depending on the number of workers. In my case I want to allow the workers to empty their inboxes on controlled termination so I don't want to use the default `brutal_kill` for the supervisor, but I also don't want to allow too much time if something hangs or is slow during this cleanup.
This PR includes:
* The new option `worker_shutdown` which can have the value `brutal_kill | timeout()`
* Add short description of option `pool_sup_shutdown` to README.md
> Add option 'worker_shutdown'

- src/wpool_process.erl
- src/wpool_utils.erl
The old code discards the original stacktrace and error class info. But the called of do_try does not handle errors we return, so we have "no case clause".
This pull request uses the behaviour we had in the original code back to 2014: we catch what we are care about and pass the error untouched otherwise.
It was the error before, every error becomes "no case clause ... in wpool_process:handle_call/3":
```erlang
09:53:02.423 [error] Supervisor mod_mam_sup had child ejabberd_mod_mam_writer_localhost_9 started with gen_server:start_link({local,ejabberd_mod_mam_writer_localhost_9}, mod_mam_rdbms_async_pool_writer, [
<<"localhost">>,9,30], []) at <0.11815.0> exit with reason {{{case_clause,function_clause},[{wpool_process,handle_call,3,[{file,"/Users/mikhailuvarov/erlang/esl/MongooseIM/_build/d …
```
> Relax scope of what we catch in do_try

- src/wpool_pool.erl
- test/wpool_pool_SUITE.erl
TL;DR: Using stored names reduces garbage by three and increases the performance (of finding the worker) by 4.
This is achieved by storing the worker names on an ets table with keys `{SupervisorName, Index}` and values the final atom representing the name, instead of calculating this atom name again and again. I suspect this might also have somehow better concurrency characteristics, as generating the name generates atoms, and therefore needs to grab locks on the atom table, which is not optimised for writes, even if the write is idempotent as the atom already exists, but this one is mostly guessing. Sequential performance is surely much better 🙂 
Not sure of the preferred conventions in this project, I'm all open for changes, mostly I'm proposing the idea more than the exact code 😇 
--- …
> Use stored worker names

- src/wpool_pool.erl
- src/wpool_queue_manager.erl
- src/wpool_sup.erl
- test/wpool_pool_SUITE.erl
Couldn't resist the temptation 😱
The PT implementation spends A LOT less time finding the pool details. At some point perfs seems to complain we now spend more time in getting the process info than anything else (grabbing the main_lock for the process and seeing the message queue length and so on, can't get any faster than that by now).
How it is all done: the wpool record contains now one more field with all the worker names as a tuple, so that not only the names are pre-generated, but also getting them is a O(1) `element(N #wpool.workers)` op. Also, `#wpool.next` is now an `atomics_ref()`, so that the rotation for the next worker doesn't take any pt modifications – the idea is from https://www.erlang.org/blog/persistent_term/ and already successfully applied by me in …
> Persistent term

- src/wpool.erl
- src/wpool_pool.erl
- test/wpool_pool_SUITE.erl
Just a bit opinionated API to manually get the worker names, in case I need to do anything manual on them. This is bordering debug purposes, but might be useful, for example for `rpc:parallel_call` a `gen_server:call` to flush their message queues, or to manually check their process state.
I figured introducing a "multicall", similar to `multicast/3`, might not be exactly what we need, as code in big pools with lots of workers would take long to execute on them sequentially, and I found introducing `rpc:parallel_call` into this library a bit of an overkill, this library's barely using those obscure OTP modules.
> Get workers API

- LICENSE
- priv/overview.edoc
- rebar.config
- src/wpool_pool.erl
- src/wpool_process.erl
- src/wpool_process_callbacks.erl
- src/wpool_utils.erl
- test/wpool_SUITE.erl
Some functions were unnecessarily exported, some others were undocumented.
> Fix the docs and do some cleanup

- .github/workflows/erlang.yml
- .gitignore
- LICENSE
- README.md
- priv/overview.edoc
- rebar.config
- src/worker_pool.app.src
- src/wpool.erl
- src/wpool_pool.erl
- src/wpool_process.erl
- src/wpool_process_callbacks.erl
- src/wpool_process_sup.erl
- src/wpool_queue_manager.erl
- src/wpool_sup.erl
- src/wpool_time_checker.erl
- src/wpool_utils.erl
- src/wpool_worker.erl
- test/crashy_server.erl
- test/echo_server.erl
- test/sleepy_server.erl
- test/wpool_SUITE.erl
- test/wpool_pool_SUITE.erl
- test/wpool_process_SUITE.erl
- test/wpool_process_callbacks_SUITE.erl
- test/wpool_worker_SUITE.erl
This isn't as big as it looks, though there's possibly a lotta changes.
I'll self-review and try to guide you through it to ease the task.
Whenever a change is not super-explicit or supported by the commit message I'll add a comment.
> Maintenance updates

- src/wpool.erl
- src/wpool_pool.erl
- test/wpool_SUITE.erl
Solves #121 but doing all the calls at once, in parallel, and then waiting for the timeouts one by one. I'm experimenting a bit with this one so I'm looking for some good feedback, if the return values are understandable, usable, if this is wanted, if the implementation is clear, etc 🙃
> Implement parallel broadcall

- README.md
- src/wpool.erl
We're not planning to implement support for anything other than gen_servers any time soon.
Tackles #194.
> Get rid of the worker_type option

- README.md
- src/wpool.erl
- src/wpool_pool.erl
- src/wpool_process.erl
- src/wpool_process_sup.erl
- src/wpool_utils.erl
- src/wpool_worker.erl
- test/wpool_SUITE.erl
Based on feedback from [this threat](https://erlangforums.com/t/need-help-understanding-the-worker-pool-by-inaka-anyone-have-any-simple-examples/3115) in the Erlang Forums, I thought of entirely reworking the documentation. I was never really a big fan of that large README file with everything, never found it much readable and most of my knowledge of the library really came from how we use it in MongooseIM. So I decided to split that big readme and move most of it to the respective types and function definitions defined in the `wpool` module, taking care of all the links working right. That also puts documentation next to the code, which might be easier to maintain in the future.
The best way to review this would be to build docs locally with `rebar3 ex_doc` and browse :)
I also added a …
> Rework documentation

- .github/workflows/erlang.yml
- .tool-versions
- rebar.config
- src/wpool_process.erl
- test/echo_server.erl
- test/wpool_process_SUITE.erl
> Adopt Erlang/OTP 27

- rebar.config
- src/wpool.erl
- src/wpool_pool.erl
- src/wpool_process.erl
- src/wpool_process_sup.erl
- src/wpool_queue_manager.erl
- src/wpool_sup.erl
- src/wpool_utils.erl
- test/wpool_SUITE.erl
- test/wpool_pool_SUITE.erl
- test/wpool_process_SUITE.erl
Far too often I already have the opts for a pool created as a map and then I have to do `maps:to_list/1`. I think maps are just way too ubiquitous these days, it's a pity not to support them 😄 
There are other cosmetic changes, like improving typespecs, upgrading plugin versions, using fully-qualified MFAs (the efficiency guide says they're somewhat faster function calls), and, increasing test coverage 🙂
> Use maps as opts (and other small cosmetic changes)

- src/wpool.erl
- src/wpool_pool.erl
- src/wpool_process_callbacks.erl
- src/wpool_process_sup.erl
- src/wpool_sup.erl
- src/wpool_utils.erl
- src/wpool_worker.erl
- test/wpool_SUITE.erl
It has been a very long time since OTP made `logger` available and deprecated `error_logger`, so it's about time we migrate to it.
Note too that we're choosing to report structured logging, that is, maps, as `worker_pool` is a library, it should allow application code to choose how to filter and format log messages.
> Migrate error_logger to logger

- rebar.config
- src/wpool.erl
- src/wpool_pool.erl
- src/wpool_process.erl
- src/wpool_queue_manager.erl
- test/echo_server.erl
- test/echo_supervisor.erl
- test/wpool_SUITE.erl
- test/wpool_pool_SUITE.erl
Sometimes a library exposes a very complex API but uses a gen_server
under the hood, and we want to pool this gen_server, but we're not
supposed to explicitly do `gen_server:call/3` nor `gen_server:cast/2`,
but use the API instead. To enable this, we expose the possibility to
run a function callback with a worker once a worker has been found.
> Extend the API with opaque runs

- src/wpool.erl
- src/wpool_pool.erl
- src/wpool_queue_manager.erl
- test/wpool_pool_SUITE.erl
This could be desired when a big pool is to do a large ton of tiny tasks _only_ in a `next_worker` or `random_worker` fashion and bombarding the queue manager with worker ready|busy will be a waste.
For the record, I'm doing exactly such thing here: https://github.com/dnsimple/erldns/blob/99592dafa06238e2629a6d099f3fd30cfbf241ff/src/listeners/erldns_proto_udp_acceptor.erl#L39 :)
> Make it possible to disable the queue manager
