- rebar.config
- src/wpool_pool.erl
@elbrujohalcon What do you think?
> added support for R18 and the deprecation of 'now'

- Makefile
- elvis.config
- rebar.config
- src/wpool.erl
- test/wpool_SUITE.erl
- test/wpool_pool_SUITE.erl
- test/wpool_process_SUITE.erl
- test/wpool_worker_SUITE.erl
A continuation of what's done on #21
> Completely remove lager

- src/wpool.erl
- src/wpool_pool.erl
- test/wpool_pool_SUITE.erl
`erlang:phash2(HashTerm, Wpool_Size)` is used to calculate an index to target a worker in the pool.
example of use:
```
wpool:cast(?MODULE,{work_harder, Tasks}, {hash_worker, UserId})
%% or
wpool:call(?MODULE,{work_harder, Tasks}, {hash_worker, UserId})
```
> Add suport for distributing work based on a hashed term

- .gitignore
- README.md
- src/worker_pool.app.src
Any interest in publishing versions to [Hex](https://hex.pm/)? Rebar3 makes it pretty convenient.
> Release on Hex?

- CHANGELOG.md
- src/worker_pool.app.src
When #37 is done, generate a release.
> Version Bump to 1.0.4

- cover.spec
- src/wpool.erl
- src/wpool_fsm_process.erl
- src/wpool_pool.erl
- src/wpool_process_sup.erl
- src/wpool_queue_manager.erl
- test/echo_fsm.erl
- test/echo_server.erl
- test/wpool_fsm_process_SUITE.erl
This is my fix for #24 
If you agree with this approach, the README file should be edited too, in order to specify the relative fsm stuff.
Please, provide feedback.
> Ferigis.24.gen fsm as a workers

- src/wpool.erl
> Fix the typespec for the hash_worker strategy

- src/wpool.erl
- src/wpool_pool.erl
- test/wpool_pool_SUITE.erl
This patch add the posisbility to pass a function to the strategy when
calling/casting/... a worker.
The function get the supervisor name as argument. To make it easy this patch
also expose the function find_wpool/1 to find the wpool record associated to a
name. Also wpool_pool:wpool_set/2, wpool_pool:wpool_get/2 have been added to
provide a transparent interface to the #wpool{} record.
Let me know if any change is needed.
> handle custom strategy functions

- README.md
This PR replaces #47 (rebasing fro
> Replacement for #47

- src/wpool_fsm_process.erl
- src/wpool_fsm_worker.erl
- src/wpool_queue_manager.erl
- test/wpool_fsm_pool_SUITE.erl
- test/wpool_fsm_worker_SUITE.erl
My fix for #46 . I have created more test cases about fsm workers.
> Ferigis.46.adding fsm tests

- CHANGELOG.md
- README.md
- src/worker_pool.app.src
[Close #62] update to 2.0.0 version
> [Close #62] update to 2.0.0 version

- elvis.config
- rebar.config
- src/wpool.erl
- src/wpool_fsm_process.erl
- src/wpool_pool.erl
- src/wpool_process.erl
- src/wpool_queue_manager.erl
- src/wpool_shutdown.erl
- test/wpool_fsm_pool_SUITE.erl
- test/wpool_pool_SUITE.erl
- test/wpool_process_SUITE.erl
For now, upgrade it to current master (inaka/katana-test#b26165d), once it's fully migrated to rebar3 we'll need to re-upgrade to the latest version.
> Upgrade katana-test

- src/wpool.erl
- src/wpool_pool.erl
I tried testing it, but ``rebar3 ct`` is not working, therefore I owe you a SUITE @elbrujohalcon .
> Added a function to retrieve the stats for all pools

- include/wpool.hrl
- src/worker_pool.app.src
- src/wpool.erl
- src/wpool_fsm_process.erl
- src/wpool_fsm_worker.erl
- src/wpool_pool.erl
- src/wpool_process.erl
- src/wpool_process_sup.erl
- src/wpool_queue_manager.erl
- src/wpool_sup.erl
- src/wpool_time_checker.erl
- src/wpool_worker.erl
- test/cover.spec
- test/crashy_server.erl
- test/echo_fsm.erl
- test/echo_server.erl
- test/wpool_SUITE.erl
- test/wpool_bench.erl
- test/wpool_fsm_pool_SUITE.erl
- test/wpool_fsm_process_SUITE.erl
- test/wpool_fsm_worker_SUITE.erl
- test/wpool_pool_SUITE.erl
- test/wpool_process_SUITE.erl
- test/wpool_worker_SUITE.erl
Indentation and ,-styles vary between different modules and sometimes within the same module.
Variable naming as well.
Let's unify those things to give the whole app a coherent style.
> Standarize code style

- test/wpool_fsm_pool_SUITE.erl
- test/wpool_pool_SUITE.erl
Due to the usage of `timer:sleep/1` some tests are behaving erratically. There must be some race conditions going on.
> Tests are unstable

- rebar.config
- src/wpool_fsm_process.erl
- src/wpool_fsm_worker.erl
- test/echo_fsm.erl
- test/wpool_fsm_pool_SUITE.erl
- test/wpool_fsm_process_SUITE.erl
Fsm coverage increased to 93% [#79]. The remaining 7% should be fixed after #80
> fsm coverage [#79]

- src/wpool_fsm_process.erl
- src/wpool_process.erl
- src/wpool_utils.erl
The common functions are shared in wpool_utils module. This fix let the coverage in 100% with the #79 issue
> [#80] Implemented shared functions in shared module. [Fix #80]

- elvis.config
- src/wpool_pool.erl
- src/wpool_time_checker.erl
- test/wpool_SUITE.erl
@elbrujohalcon I would say you need to review this PR's SUITE extra carefully.
> Added support for multiple overrun handlers and fixed the tests

- src/wpool_pool.erl
> Remove useless ets creation info message

- CHANGELOG.md
- src/worker_pool.app.src
> [#91] Version Bump to 2.2.2

- .travis.yml
- README.md
- ci
> [#109] Adding Travis

- CHANGELOG.md
- src/worker_pool.app.src
> Publish latest version to hex?

- src/wpool_pool.erl
- src/wpool_process.erl
- test/echo_server.erl
- test/wpool_process_SUITE.erl
At least, we need to support `gen_server:handle_continue/2`, but maybe more things.
> Adjust to OTP21

- README.md
I replaced the links in the readme to point to the hexdocs page +  some minor changes.
> [#165] Fix broken links

- README.md
Hopefully solves #122 
@elbrujohalcon I had a ton of ideas on why this strategy is so nice for me in MongooseIM, but I didn't want to put examples here from that specific domain, so my paragraph on the documentation is quite brief(er than I'd usually do full talkative mode). What do you think? 😄
> Document hash_worker strategy

- README.md
- rebar.config
For integration into projects where can be supported OTP 21
> Decrease 'minimum_otp_vsn' to '21'

- src/wpool_pool.erl
A few tiny optimisations, see commit by commit for more details.
> Small perf improvements

- rebar.config
> Update plugin vsns

- .github/workflows/erlang.yml
This is the last one in the barrage of pull requests. I had these pending locally, don't remember why. Sorry about that, @elbrujohalcon.
> Be less wasteful of CI

- .github/workflows/erlang.yml
We're making sure pushing to the main branch, as well as pull requests, and workflow dispatches, trigger CI.
> Fix CI execution conditions: pull request + push to main
